### ISSUE TITLE
Support for Portfolio margin 

### ISSUE THREAD

**Issue by liujdream** [tiagosiebler/binance#454] opened 2024-09-24 07:39 UTC
it seems the newest package doesn't support portfolio margin yet (base endpoint: https://papi.binance.com/)
Curious if there is any plan to add the support?

**Comment by tiagosiebler** [comment] 2024-09-26 06:47
Hi @liujdream - yes, I've actually worked through a lot of it already but I'm unable to test it as I'm regionally blocked from enabling portfolio margin mode. If you could provide read-only API keys to a sub account (empty sub account is fine if preferred), that would give me everything needed to test this and get the release of a PM client finished. 

If you're happy to do so, please get in touch. One place to chat is telegram, where I also have an active community: https://t.me/AlgoTraderL

**Comment by tiagosiebler** [comment] 2024-11-04 09:01
Duplicate of #428, subscribe to that issue to follow. Currently fleshing out & testing PM support.

**Closed by tiagosiebler** 2024-11-04 09:01 UTC
