### ISSUE TITLE
subscribeSpotTrades does not emit `formattedMessage`

### ISSUE THREAD

**Issue by caiusCitiriga** [tiagosiebler/binance#266] opened 2022-11-24 22:45 UTC

**Comment by tiagosiebler** [comment] 2022-11-24 22:59
Duplicate of #267

**Closed by tiagosiebler** 2022-11-24 22:59 UTC

**Comment by caiusCitiriga** [comment] 2022-11-24 23:01
WTF 😱 why do I have 2 issues with same title and no body?! Sorryyyyyy 🙏🏻

**Comment by tiagosiebler** [comment] 2022-11-24 23:29
Haha no worries, I've somehow done this before too 😁
