### ISSUE TITLE
The result of "onAllTickers" Websocket method give me a string

### ISSUE THREAD

**Issue by christiandbf** [tiagosiebler/binance#54] opened 2018-03-15 22:17 UTC
I am using the "onAllTickers" Web-socket method to check conditions in the markets. The method works fine, normally I receive the Array with the values like it is expected to work. But suddenly I receive a String and not a Array.

You can try the following code, to see what I am trying to explain.

```
const api = require('binance')
const ws = new api.BinanceWS(true)

ws.onAllTickers(data => {
  console.log(typeof data)
})
```

**Comment by tiagosiebler** [comment] 2020-03-17 20:40
@christiandbf do you still see this issue, can you still reproduce it? 

If so, can you provide:
- an example string of what you see when this wasn't an array (it's ok to attach as text file)
- an example stringified (`JSON.stringify(data)`) sample of what you see when this was an array, in case it's useful
- how often do you see this happening? once every few minutes/hours/days/weeks?

**Comment by tiagosiebler** [comment] 2021-05-19 00:25
closing due to no reply

**Closed by tiagosiebler** 2021-05-19 00:25 UTC
Labels: bug, question
